DROP TABLE IF EXISTS "carts";
DROP TABLE IF EXISTS "products";
DROP TABLE IF EXISTS "users";
DROP TABLE IF EXISTS "shops";
DROP TABLE IF EXISTS "orders";
DROP TABLE IF EXISTS "invoice";
DROP TABLE IF EXISTS "shipping";