// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"encoding/json"
	"time"
)

type Category struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Order struct {
	ID int64 `json:"id"`
	// to know which user has an order
	UserID    int64           `json:"user_id"`
	Items     json.RawMessage `json:"items"`
	CreatedAt time.Time       `json:"created_at"`
	UpdatedAt time.Time       `json:"updated_at"`
}

type Product struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
	// description of the item
	Description     string    `json:"description"`
	Price           string    `json:"price"`
	Images          []string  `json:"images"`
	QtyAval         int32     `json:"qty_aval"`
	ShopID          int64     `json:"shop_id"`
	ShopName        string    `json:"shop_name"`
	CategoryID      int64     `json:"category_id"`
	CategoryName    string    `json:"category_name"`
	SubCategoryID   int64     `json:"sub_category_id"`
	SubCategoryName string    `json:"sub_category_name"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

type Shop struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Phone     string    `json:"phone"`
	Address   string    `json:"address"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type SubCategory struct {
	ID           int64     `json:"id"`
	Name         string    `json:"name"`
	CategoryID   int64     `json:"category_id"`
	CategoryName string    `json:"category_name"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type User struct {
	ID             int64     `json:"id"`
	Lastname       string    `json:"lastname"`
	Firstname      string    `json:"firstname"`
	HashedPassword string    `json:"hashed_password"`
	Phone          string    `json:"phone"`
	Address        string    `json:"address"`
	Email          string    `json:"email"`
	IsAdmin        bool      `json:"is_admin"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}
